apiVersion: v1
kind: ConfigMap
metadata:
  name: "web-app-config"
data:
  # When the config map is mounted as a volume, these will be created as files.
  web.json: '{
    "disableAuthenticationFeatures": {{ .Values.disableAuthenticationFeatures }},
    "baseUrl": {{ .Values.baseUrl | default "/" | quote }}
  }'