language: node_js
node_js:
- '6'
script:
- pip install --user --upgrade awscli
- npm test
- npm config set magda-web:awsProfile ""
- npm config set magda-web:awsS3Dir $TRAVIS_BRANCH
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then yarn run deploy-without-reinstall; fi
env:
  global:
  - secure: Z05S5EnUl/NMUGmFOqlnOhni2ILUaClCxrmUoCY5zzuFXilc/TSsBJEFJLxe1Vfa6U5zkNUepPfvYlw/Y6Mc1Oj1sxGw83r9tW336GCWbYbNC7A16DvcCNRDQEyNVFsI4je2vo8VmizvKcrnCKulDuBpRdLV0hpKaw8MSpyOu93cFSFxwoxt+odCh+2330qvVD4LsslOyOHyJ/RNSME0JuUoCxN5S6MqxmacdJqqnaPWZJQ7Jz0lB4qvZpebE/SMXsL7Dbe+CqBw5oYLlqsq0kWXHon7O73Q8RKmXhHTea2ivBz6vX8t5O6e9Ggj6Q0OTgCyo7dPMBwQk43WQ3K3O/LJ8MVgTcDCrPf54hi0JEUc96a6CEZgMIWQp9rdsQLg7xmg+jbJhXKAcEXs6lUv7S+w7PpRRam2k4ft49RDUeiGAfJCLjg8ZgK9J5w/5rlae08u5ZBIUqGLp7WCUlmN0lPx5QVYbrToVM/i6pmj3J+uyof6ViWLNC6DdWpr4gzV/64Qa7EovZoYfYrL9fskusvnwxTcLcZEg4W0AR9IarWwPb6XgFG1N0ffJctfNDAty69YW2lH5p1WSlKu5xjCfKsZSwlZDfW+MgJXL4r2xNvSf0fH8CNdor8UyyIYrm1ukakT0S+iUCwbO3PVez35qavWHn24AHQ/QeX9/QufNRE=
  - secure: O1CcGXVK/JMwMFw8bKIGMohy0yjWOw59KSCbjGSyiiUWo6tZmhYPOrR4EPgn7ra1sLCUcpVoCHdlvFh5T/Z6dPXRdJBSrA1C5szAVwBMoNwwKVHnugbpatq0Ga4WvB0JoCV4NVvoT7AUdSq9UovLlluR1FWRBzKQNT6Etzl6qQ9cSGf0IV4wyg2ONp4d3CWd4OqchEJjlFid6ilF4zwO1/7x5GIZZyODktpjdmDkrh/jO3qoq/u2pORB9wJkYB3/aVG5OmmpbJSvJ2jIiYS21kTYQNVqc2lNhYZBizl8i6689i9i/f9cOsDeEMZiyTujbG019MHh6MTBUuzCPCUvg07z48KPTAePcW8CZWxrKSh2pUaAlzmj7sCh2EQVGE+GDy4RgosZs3AeT2kPfA9J29nKUBQJAkEq7TAvVDOzP2CyUw4WO5v5aR19YGGvEGimBszMqD1KQli5byVPLYdxafv/rbW6ESAp+Ghvc6izM8hVPJH4Ol43HWHPYZx+ZKnrYAeUFn5Rin24dSJ+MsvZZXMzlsyYmslWBYghPV+NXpjP8tiZqNu5M/uFn9GzV/TWIfixVomn9AOxKYs75RjxKGTH+2vd3uLTOab97aQ9DNXIdLCFJN+fVSYlp7m3NYEl1Hn0vHwDIN1hlWyJHAsLBRkraIX0SjVBWsRTTbY3LYQ=
